config/routes.rb
Rails.application.routes.draw do
    # Home Page
    root 'pages#home'

    use_doorkeeper

    # Devise User Routes
    devise_for :users

    # Sentence Transformations Routes
    resources :sentence_transformations

    # Draw Api Routes
    draw :api
end

app/models/sentence_transformation.rb
class SentenceTransformation < ApplicationRecord
end

app/controllers/api/v1/sentence_transformations_controller.rb
class Api::V1::SentenceTransformationsController < ApiController
    before_action :set_sentence_transformation, only: %i[ show edit update destroy ]

    # GET /sentence_transformations or /sentence_transformations.json
    def index
        @sentence_transformations = SentenceTransformation.all
        render json: @sentence_transformations
    end


    # GET /sentence_transformations/1 or /sentence_transformations/1.json
    def show
    end


    # GET /sentence_transformations/new
    def new
        @sentence_transformation = SentenceTransformation.new
    end


    # GET /sentence_transformations/1/edit
    def edit
    end


    # POST /sentence_transformations or /sentence_transformations.json
    def create
        @sentence_transformation = SentenceTransformation.new(sentence_transformation_params)

        respond_to do |format|
            if @sentence_transformation.save
                format.html { redirect_to sentence_transformation_url(@sentence_transformation), notice: "Sentence transformation was successfully created." }
                format.json { render :show, status: :created, location: @sentence_transformation }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @sentence_transformation.errors, status: :unprocessable_entity }
            end
        end
    end


    # PATCH/PUT /sentence_transformations/1 or /sentence_transformations/1.json
    def update
        respond_to do |format|
            if @sentence_transformation.update(sentence_transformation_params)
                format.html { redirect_to sentence_transformation_url(@sentence_transformation), notice: "Sentence transformation was successfully updated." }
                format.json { render :show, status: :ok, location: @sentence_transformation }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @sentence_transformation.errors, status: :unprocessable_entity }
            end
        end
    end


    # DELETE /sentence_transformations/1 or /sentence_transformations/1.json
    def destroy
        @sentence_transformation.destroy

        respond_to do |format|
            format.html { redirect_to sentence_transformations_url, notice: "Sentence transformation was successfully destroyed." }
            format.json { head :no_content }
        end
    end





    private



    # Use callbacks to share common setup or constraints between actions.
    def set_sentence_transformation
        @sentence_transformation = SentenceTransformation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sentence_transformation_params
        params.require(:sentence_transformation).permit(:original, :keyword, :partial, :answer)
    end
end

app/controllers/sentence_transformations_controller.rb
class SentenceTransformationsController < ApplicationController
    before_action :set_sentence_transformation, only: %i[ show edit update destroy ]
    before_action :authenticate_user!

    # GET /sentence_transformations or /sentence_transformations.json
    def index
        @sentence_transformations = SentenceTransformation.all
    end

    # GET /sentence_transformations/1 or /sentence_transformations/1.json
    def show
    end

    # GET /sentence_transformations/new
    def new
        @sentence_transformation = SentenceTransformation.new
    end

    # GET /sentence_transformations/1/edit
    def edit
    end

    # POST /sentence_transformations or /sentence_transformations.json
    def create
        @sentence_transformation = SentenceTransformation.new(sentence_transformation_params)

        respond_to do |format|
            if @sentence_transformation.save
                format.html { redirect_to sentence_transformation_url(@sentence_transformation), notice: "Sentence transformation was successfully created." }
                format.json { render :show, status: :created, location: @sentence_transformation }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @sentence_transformation.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /sentence_transformations/1 or /sentence_transformations/1.json
    def update
        respond_to do |format|
            if @sentence_transformation.update(sentence_transformation_params)
                format.html { redirect_to sentence_transformation_url(@sentence_transformation), notice: "Sentence transformation was successfully updated." }
                format.json { render :show, status: :ok, location: @sentence_transformation }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @sentence_transformation.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /sentence_transformations/1 or /sentence_transformations/1.json
    def destroy
        @sentence_transformation.destroy

        respond_to do |format|
            format.html { redirect_to sentence_transformations_url, notice: "Sentence transformation was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_sentence_transformation
        @sentence_transformation = SentenceTransformation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sentence_transformation_params
        params.require(:sentence_transformation).permit(:original, :keyword, :partial, :answer)
    end
end

app/helpers/sentence_transformations_helper.rb
module SentenceTransformationsHelper
end

app/views/sentence_transformations/_form.html.erb
<%= form_with(model: sentence_transformation) do |form| %>
  <% if sentence_transformation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sentence_transformation.errors.count, "error") %> prohibited this sentence_transformation from being saved:</h2>

      <ul>
        <% sentence_transformation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :original, style: "display: block" %>
    <%= form.text_field :original %>
  </div>

  <div>
    <%= form.label :keyword, style: "display: block" %>
    <%= form.text_field :keyword %>
  </div>

  <div>
    <%= form.label :partial, style: "display: block" %>
    <%= form.text_field :partial %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_field :answer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sentence_transformations/_sentence_transformation.html.erb
<div id="<%= dom_id sentence_transformation %>">
  <p>
    <strong>Original:</strong>
    <%= sentence_transformation.original %>
  </p>

  <p>
    <strong>Keyword:</strong>
    <%= sentence_transformation.keyword %>
  </p>

  <p>
    <strong>Partial:</strong>
    <%= sentence_transformation.partial %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= sentence_transformation.answer %>
  </p>

</div>

app/views/sentence_transformations/edit.html.erb
<h1>Editing sentence transformation</h1>

<%= render "form", sentence_transformation: @sentence_transformation %>

<br>

<div>
  <%= link_to "Show this sentence transformation", @sentence_transformation %> |
  <%= link_to "Back to sentence transformations", sentence_transformations_path %>
</div>

app/views/sentence_transformations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sentence transformations</h1>

<div id="sentence_transformations">
  <% @sentence_transformations.each do |sentence_transformation| %>
    <%= render sentence_transformation %>
    <p>
      <%= link_to "Show this sentence transformation", sentence_transformation %>
    </p>
  <% end %>
</div>

<%= link_to "New sentence transformation", new_sentence_transformation_path %>

app/views/sentence_transformations/new.html.erb
<h1>New sentence transformation</h1>

<%= render "form", sentence_transformation: @sentence_transformation %>

<br>

<div>
  <%= link_to "Back to sentence transformations", sentence_transformations_path %>
</div>

app/views/sentence_transformations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sentence_transformation %>

<div>
  <%= link_to "Edit this sentence transformation", edit_sentence_transformation_path(@sentence_transformation) %> |
  <%= link_to "Back to sentence transformations", sentence_transformations_path %>

  <%= button_to "Destroy this sentence transformation", @sentence_transformation, method: :delete %>
</div>